document_exporter_report/document_exporter_report/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('excel_report_generator.urls')),
]

document_exporter_report/excel_report_generator/urls.py
from django.urls import path
from .views import Index, success

app_name = 'excel_report_generator'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('success/<filepath>/', success, name='success')
]

document_exporter_report/excel_report_generator/models.py
from django.db import models
from datetime import datetime
import os


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    PARSERS_CHOICES = (
        (1, 'Parser 1'),
        (2, 'Parser 2'),
        (3, 'Parser 3'),
        (4, 'Parser 4'),
        (5, 'Parser 5'),
        (6, 'Parser 6'),
        (7, 'Parser 7'),
        (8, 'Parser 8'),
        (9, 'Parser 9'),
        (10, 'Parser 10'),
    )
    parser = models.IntegerField(choices=PARSERS_CHOICES)

    def __str__(self):
        return '{}'.format(self.name)


def file_path_and_name(instance, filename):
    base_file_name, file_extension = os.path.splitext(filename)
    _now = datetime.now()
    return 'uploads/{basename} {date} {time} {ext}'.format(
        basename=base_file_name, ext=file_extension,
        date=_now.strftime('%Y-%m-%d'), time=_now.strftime('%H:%M:%S')
    )


class FileParser(models.Model):
    id = models.AutoField(primary_key=True)
    email_id = models.IntegerField()
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    email_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    parser = models.TextField()
    OPTIONS = (
        (100, 'by email'),
        (200, 'uploaded by user'),
    )
    options = models.IntegerField(choices=OPTIONS)
    sent = models.BooleanField()
    file = models.FileField(upload_to=file_path_and_name)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.email_date)

document_exporter_report/excel_report_generator/forms.py
from .models import Customer
from django import forms


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer

        fields = [
            'name',
        ]
        labels = {
            'name': 'Name',
        }
        widgets = {
            'name': forms.Select(),
        }

document_exporter_report/excel_report_generator/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.views.generic.base import View
from .models import Customer
import logging
import datetime
import os
from django.conf import settings
from .tasks import create_excel
from celery import signature


class Index(View):

    @staticmethod
    def get(request):
        customer = Customer.objects.all()
        context = {'customer': customer}
        return render(request, 'document_exporter_report/index.html', context)

    @staticmethod
    def post(request):
        customer = request.POST['customer']
        filter = request.POST['filter']
        try:
            checkbox = request.POST['checkbox']
        except Exception as e:
            checkbox = 'off'
            logging.debug("error", e)
        date_range = request.POST['date_range']
        data_split = date_range.split(" - ")
        initial_date_string = data_split[0]
        initial = datetime.datetime.strptime(initial_date_string, '%m/%d/%Y')
        finished_date_string = data_split[1]
        finish = datetime.datetime.strptime(finished_date_string, '%m/%d/%Y')
        file_path = create_excel.s(customer, filter, initial, finish, checkbox)
        context = {'file_path': file_path}
        return render(request, 'document_exporter_report/download.html', context)


def success(request, filepath):
    context = {}
    filepath = 'Reports/' + filepath
    file_path = os.path.join(settings.MEDIA_ROOT, filepath)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            # response['Refresh'] = "0;url=/success"
            return response
    raise Http404

document_exporter_report/templates/document_exporter_report/download.html
{% extends 'adminlte/base.html' %}

{% block content %}
     <div class="col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h4>Report generated successfully!</h4>
            </div>
              <div class="box-footer">
                  <a href="{% url 'excel_report_generator:success' file_path %}" type="button" class="btn btn-success" target="_blank">Download</a>
              </div>

          </div>
    </div>
    {% endblock %}

document_exporter_report/templates/document_exporter_report/success.html
{% extends 'adminlte/base.html' %}
    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <meta http-equiv="Refresh" content="0;url=/success">
    {% endblock %}
{% block content %}
      <div class="col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h4>Successful download!</h4>
            </div>
              <div class="box-footer">
                  <a href="/" type="button" class="btn btn-success">Home</a>
              </div>

          </div>
    </div>

{% endblock %}